server:
  port: 8080
spring:
  data:
    mongodb:
      host: 192.168.20.180
      port: 27017
      database: demo
    redis:
      port: 6379
      host: 192.168.20.56
      database: 6
      password: password
logging:
  level:
    root: info
  file:
    name: demoLog.log
jwt:
  secret: MBodiT5I025fuE1bg2MT6jTs6vUpjoYefjRR0SiWjwk=
  expiration: 86400